{{- if .Values.clusterDnsSync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole.name" . }}-dns-sync
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
data:
  sync.sh: |
{{- .Files.Get "files/dns-sync.sh" | trim | nindent 4 }}
{{- end }}
