apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pihole.name" . }}-data
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistenceSize }}
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end }}
