{{- if and (not .Values.existingSecret.name) .Values.webPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole.name" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
type: Opaque
stringData:
  password: {{ .Values.webPassword | quote }}
{{- end }}
