#!/bin/sh
# Avoid set -e: pipelines (e.g. grep) may be non-zero during normal IPv4 selection.
OUT="/etc/dnsmasq.d/03-k8s-nodes.conf"
DOMAIN="${LOCAL_DOMAIN:-lan}"
INTERVAL="${SYNC_INTERVAL:-300}"

ftl_pid() {
  pidof pihole-FTL 2>/dev/null || ps aux 2>/dev/null | awk '/[p]ihole-FTL/ {print $2; exit}'
}

reload_dns() {
  FTL_PID=$(ftl_pid)
  if [ -z "$FTL_PID" ]; then
    return 0
  fi
  if chroot "/proc/${FTL_PID}/root" /usr/local/bin/pihole restartdns 2>/dev/null; then
    echo "pihole restartdns OK"
    return 0
  fi
  if kill -HUP "$FTL_PID" 2>/dev/null; then
    echo "SIGHUP pihole-FTL OK"
    return 0
  fi
  echo "WARN: could not reload Pi-hole DNS; changes apply on next FTL restart"
}

write_nodes() {
  if ! NAMES=$(kubectl get nodes -o jsonpath='{.items[*].metadata.name}' 2>/dev/null); then
    return 1
  fi
  TMP=$(mktemp)
  {
    echo "# Generated by pihole-dns-sync — do not edit"
    for name in $NAMES; do
      [ -z "$name" ] && continue
      # Dual-stack nodes report multiple InternalIPs; Pi-hole LAN records need one IPv4.
      ip=$(kubectl get node "$name" -o jsonpath='{range .status.addresses[?(@.type=="InternalIP")]}{.address}{"\n"}{end}' 2>/dev/null | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -1)
      [ -z "$ip" ] && continue
      echo "address=/${name}.${DOMAIN}/${ip}"
    done
  } >"$TMP"
  if [ ! -f "$OUT" ] || ! cmp -s "$TMP" "$OUT" 2>/dev/null; then
    mv "$TMP" "$OUT"
    echo "Updated $OUT"
    reload_dns
  else
    rm -f "$TMP"
  fi
}

echo "Waiting for pihole-FTL..."
i=0
while [ "$i" -lt 120 ]; do
  pid=$(ftl_pid)
  [ -n "$pid" ] && break
  i=$((i + 1))
  sleep 1
done

while true; do
  write_nodes || echo "WARN: sync failed, retry in ${INTERVAL}s"
  sleep "$INTERVAL"
done
