#!/bin/bash
# Set a node's wlan0 to a static IP using netplan.
# WiFi SSID/PSK from config/project.env. Node's current IP from config/nodes.
#
# **Static on Ethernet instead (Pi):** see **`nodes/modera-rpi5.md`** (2026-03-29). On a Pi with
# NetworkManager, use **`nmcli`** to move **`192.168.1.5`** from **`wlan0`** to **`eth0`**, set **`wlan0`**
# to DHCP, then add **`/etc/systemd/system/k3s-agent.service.d/node-ip.conf`** with
# **`k3s agent --node-ip=<eth0 IPv4>`** so Flannel matches the wired address.
#
# Usage: ./scripts/set-node-static-ip.sh <hostname> <static_ip/cidr> [gateway]
# Example: ./scripts/set-node-static-ip.sh mynode 192.168.1.5/24 192.168.1.1
#
# After running, update config/nodes with the new IP and run ./scripts/ssh-config-from-nodes.sh.
# On many routers (e.g. GFiber): reserve the static IP for the node's MAC in DHCP settings
# so the router doesn't assign that address to another device.

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

[ -f "$REPO_ROOT/config/defaults.env" ] && . "$REPO_ROOT/config/defaults.env"
[ -f "$REPO_ROOT/config/project.env" ] && . "$REPO_ROOT/config/project.env"

if [ $# -lt 2 ]; then
  echo "Usage: $0 <hostname> <static_ip/cidr> [gateway]" >&2
  echo "Example: $0 mynode 192.168.1.5/24 192.168.1.1" >&2
  exit 1
fi

NODE_HOSTNAME="$1"
STATIC_IP_CIDR="$2"
GATEWAY="${3:-192.168.1.1}"
NAMESERVERS="${4:-192.168.1.1}"

if [ -z "${K3S_WIFI_SSID}" ] || [ -z "${K3S_WIFI_PSK}" ]; then
  echo "Set K3S_WIFI_SSID and K3S_WIFI_PSK in config/project.env." >&2
  exit 1
fi

if [ ! -f "$REPO_ROOT/config/nodes" ]; then
  echo "config/nodes not found." >&2
  exit 1
fi
NODE_CURRENT_IP=$(grep -E "^${NODE_HOSTNAME}\s+" "$REPO_ROOT/config/nodes" | awk '{print $2}')
if [ -z "$NODE_CURRENT_IP" ]; then
  echo "Hostname '${NODE_HOSTNAME}' not found in config/nodes." >&2
  exit 1
fi

# Escape single quotes in PSK for YAML
SAFE_PSK=$(echo "$K3S_WIFI_PSK" | sed "s/'/'\\\\''/g")

NETPLAN_YAML=$(cat << EOF
# Static IP for ${NODE_HOSTNAME} (K3s homelab). Generated by scripts/set-node-static-ip.sh
network:
  version: 2
  wifis:
    wlan0:
      dhcp4: false
      addresses: [${STATIC_IP_CIDR}]
      routes:
        - to: default
          via: ${GATEWAY}
      nameservers:
        addresses: [${NAMESERVERS}]
      access-points:
        ${K3S_WIFI_SSID}:
          password: '${SAFE_PSK}'
      optional: false
EOF
)

echo "Applying static IP ${STATIC_IP_CIDR} (gateway ${GATEWAY}) on ${NODE_HOSTNAME} wlan0..."

TMP_YAML=$(mktemp)
trap 'rm -f "$TMP_YAML"' EXIT
echo "$NETPLAN_YAML" > "$TMP_YAML"

REMOTE_FILENAME="99-static-wlan0.yaml"
sshpass -p "$K3S_NODE_PASSWORD" scp -o StrictHostKeyChecking=no "$TMP_YAML" \
  "$K3S_SSH_USER@$NODE_CURRENT_IP:/tmp/$REMOTE_FILENAME"

sshpass -p "$K3S_NODE_PASSWORD" ssh -T -o StrictHostKeyChecking=no "$K3S_SSH_USER@$NODE_CURRENT_IP" \
  "echo \"$K3S_NODE_PASSWORD\" | sudo -S mv /tmp/$REMOTE_FILENAME /etc/netplan/$REMOTE_FILENAME && echo \"$K3S_NODE_PASSWORD\" | sudo -S netplan apply"

echo "Netplan applied. ${NODE_HOSTNAME} should now be at ${STATIC_IP_CIDR}."
echo "Next: update config/nodes to '${NODE_HOSTNAME} <new_ip>', then run ./scripts/ssh-config-from-nodes.sh"