#!/bin/bash
# Interactive first-time project config. Writes config/project.env (gitignored).
# Run from repo root: ./scripts/setup-project.sh

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$REPO_ROOT/config"
ENV_FILE="$CONFIG_DIR/project.env"

cd "$REPO_ROOT"
mkdir -p "$CONFIG_DIR"
[ -f "$REPO_ROOT/config/defaults.env" ] && . "$REPO_ROOT/config/defaults.env"

if [ -f "$ENV_FILE" ]; then
  echo "Existing config: $ENV_FILE"
  read -p "Overwrite? [y/N] " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[yY]$ ]]; then
    echo "Aborted."
    exit 0
  fi
fi

echo ""
echo "K3s homelab — project config (first-time setup)"
echo "Press Enter to accept [default from config/defaults.env]. Leave password empty to set it later."
echo ""

read -p "SSH user on nodes [${K3S_SSH_USER:-serendipper}]: " inp
K3S_SSH_USER="${inp:-${K3S_SSH_USER:-serendipper}}"

read -p "Path to SSH private key [${K3S_SSH_KEY:-$HOME/.ssh/k3s_ed25519}]: " inp
K3S_SSH_KEY="${inp:-${K3S_SSH_KEY:-$HOME/.ssh/k3s_ed25519}}"

read -p "SSH known_hosts file [${K3S_SSH_KNOWN_HOSTS:-$HOME/.ssh/known_hosts}]: " inp
K3S_SSH_KNOWN_HOSTS="${inp:-${K3S_SSH_KNOWN_HOSTS:-$HOME/.ssh/known_hosts}}"

read -sp "Node login + sudo password (optional; leave empty to set later): " K3S_NODE_PASSWORD
echo ""

read -p "Wi‑Fi SSID for nodes [${K3S_WIFI_SSID:-}]: " inp
K3S_WIFI_SSID="${inp:-${K3S_WIFI_SSID}}"

read -sp "Wi‑Fi password (PSK) for nodes (optional; leave empty to set later): " K3S_WIFI_PSK
echo ""

read -p "Control plane IP (for join URL / jump host; or resolve from config/nodes) [${K3S_CP_IP:-}]: " inp
K3S_CP_IP="${inp:-${K3S_CP_IP}}"

read -p "PostgreSQL datastore URL (control plane; optional; leave empty to set later): " K3S_DATASTORE_URL

# Write project.env
{
  echo "# K3s homelab — project config (generated by scripts/setup-project.sh)"
  echo "# project.env is gitignored; do not commit secrets."
  echo ""
  echo "K3S_SSH_USER=$K3S_SSH_USER"
  echo "K3S_SSH_KEY=$K3S_SSH_KEY"
  echo "K3S_SSH_KNOWN_HOSTS=$K3S_SSH_KNOWN_HOSTS"
  echo "K3S_NODE_PASSWORD=$K3S_NODE_PASSWORD"
  echo "K3S_WIFI_SSID=$K3S_WIFI_SSID"
  if [ -n "$K3S_WIFI_PSK" ]; then
    echo "K3S_WIFI_PSK=$K3S_WIFI_PSK"
  else
    echo "# K3S_WIFI_PSK="
  fi
  echo "K3S_CP_IP=$K3S_CP_IP"
  if [ -n "$K3S_DATASTORE_URL" ]; then
    echo "K3S_DATASTORE_URL=$K3S_DATASTORE_URL"
  else
    echo "# K3S_DATASTORE_URL="
  fi
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
echo ""
echo "Wrote $ENV_FILE"
echo "Next: run agent-environment-setup (generate key, SSH config, deploy keys)."
